### ISSUE TITLE
Base hash behind, can't talk to star

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#12]
~wicpec-marzod

What's the preferred method for forcing your base hash up to date?

**Comment by vvisigoth** [comment]
It looks like your planet is under an inactive star (and galaxy). You'll need to request a sponsor change at https://urbit.org/using/operations/using-your-ship/#escaping-a-sponsor

**Comment by baudtack** [comment]
Do you need help getting your planet transferred?
