### ISSUE TITLE
Can't get through install

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#14]
~pannys-toppem receives permission denied. Possible Window/Ubunto error?

Installed Ubuntu 18.04 LTS, and got WSL 2
I've followed the install + setup guide but can't get past: ./urbit -w sampel-palnet -k path/to/my-planet.key

![](https://user-images.githubusercontent.com/45108193/80994908-a81c7880-8dfa-11ea-9ea4-674be782446b.png)

**Comment by crrncllns** [comment]
![6739D633-D6B0-4CB9-9F80-DF66B3170F6E](https://user-images.githubusercontent.com/45108193/80994908-a81c7880-8dfa-11ea-9ea4-674be782446b.png)

**Comment by drbeefsupreme** [comment]
It looks like a permission error, namely that you do not have permission to read the key file. You should be able to take ownership of the file by running `sudo chown <your-username> /home/jacob/pannys-toppem-1.key` (remove the <> around your username).

If that doesn't work, its probably something related to WSL2, which I don't know much about.

**Comment by QuixoticRust** [comment]
> It looks like a permission error, namely that you do not have permission to read the key file. 

Yep, along those lines I got it working. When I tried running the key file it told me it required permission to write. Even after running `sudo chown ...` I eventually got it working using `sudo chmod -R a+rwx /path/to/folder`
(Source: https://ostoday.org/linux/how-to-give-permission-to-user-in-linux.html)

Thanks for the help!

**Comment by drbeefsupreme** [comment]
Made into a wiki page: https://github.com/urbit/urbit/wiki/%22Permission-denied%22-for-key-when-dawning-ship
