### ISSUE TITLE
Can't join ~/~dopzod/urbit-help

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#17]
Tried on command line from chat-cli app and Landscape

![image-1](https://user-images.githubusercontent.com/45108193/81240552-e9608400-8fc4-11ea-81cc-70e262d22d45.png)

**Comment by tyconway** [comment]
How come this was closed?

**Comment by crrncllns** [comment]
We're changing our support process a bit—your request is still open, but we'll handle it through email. Sorry for the confusion!

**Comment by tyconway** [comment]
Of course, that’s perfect! Thank you.
