### ISSUE TITLE
Incomplete star transfer

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#18]
Steps
In Bridge—Galaxy, “Issue Child Point.” Picks a star and destination address. Error: “This point cannot be spawned" regardless of point chosen.

Star Release shows 19 stars available to withdraw. Using Trezor.

![Screen Shot 2020-05-07 at 9 15 07 AM](https://user-images.githubusercontent.com/45108193/81315056-0fc70380-9047-11ea-9729-208638c9dd0c.png)

**Comment by vvisigoth** [comment]
@syzygyzer I'd get @Fang- to help with this

**Comment by Fang-** [comment]
Well, ~fopwex is owned by the star release contract, so you can indeed not just spawn it. I'm not sure why it's being suggested as an example point, I thought we pulled those examples from the "actually available" hat. So that's a Bridge bug.

**Comment by vvisigoth** [comment]
@Fang- is this already an issue in Bridge repo?

**Comment by Fang-** [comment]
This seems to fall within urbit/bridge#400, yeah.
