### ISSUE TITLE
Ethereum transaction hangs

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#20]
~dindex-tabdes  
![image](https://user-images.githubusercontent.com/45108193/81831688-e866af80-94fa-11ea-91fd-e32ed6faad9e.png)

**Comment by drbeefsupreme** [comment]
You need to do what is said in the box - put some more ETH in the address.

**Comment by drbeefsupreme** [comment]
Sorry, I think I am mistaken. I've had to do that before but it should actually be funded for you automatically. Someone else was having the same problem and it went through. Can you try again?

**Comment by drbeefsupreme** [comment]
https://github.com/urbit/support/wiki/Ethereum-transaction-in-Bridge-hangs-when-either-creating-a-new-planet-or-breaching
