### ISSUE TITLE
Ethereum transaction hangs

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#21]
Tries to activate new planet, stuck at last step. It's been sitting there for far more than 5 minutes, close to an hour

![unnamed](https://user-images.githubusercontent.com/45108193/81838302-2e277600-9503-11ea-8174-e4df3ab72cf7.png)

**Comment by kennyrowe** [comment]
Looks like this has processed now, but we'll look into why it was delayed

**Comment by crrncllns** [comment]
![unnamed-1](https://user-images.githubusercontent.com/45108193/81852424-3938d100-9518-11ea-9d53-4b90ea0fe106.png)
 
Eventually processed transaction ok

**Comment by drbeefsupreme** [comment]
https://github.com/urbit/support/wiki/Ethereum-transaction-in-Bridge-hangs-when-either-creating-a-new-planet-or-breaching
