### ISSUE TITLE
Empty base hash

### ISSUE THREAD

**Issue by cxk280** [urbit/support#26]
I run `~ripten`. My latest `+trouble` returns the following:

```
[ [%base-hash ~]
  [%sour-hash 0v0]
  [%home-hash 0v14.rhjk7.f066u.2gn21.8banh.gcov0.6rmv0.rjkvp.jqf05.lb3im.nlch2]
  [%kids-hash 0v14.rhjk7.f066u.2gn21.8banh.gcov0.6rmv0.rjkvp.jqf05.lb3im.nlch2]
  [%glob-hash 0v3.i5rmt.7fid4.sr9bh.0pcpi.cmc0v %done]
  [%our ship=~ripten point='38816' life=[~ 4] rift=[~ 5]]
  [%sponsor ship=~ten point='160' life=[~ 4] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

Why is `base-hash` just `~`? How do I fix it?

I found this issue when investigating why a child planet of this star has the base hash `0va.pul07.ph10n.dnbh7.78e73.hav2t.ae9ik.jegg5.dqm2t.5baqv.mnqtc`, which does not seem to correspond with any actual releases. Would these problems be related? If not, I need help debugging the child planet's hash issue too.

I followed the instructions [here](https://github.com/urbit/support/wiki/Missing-OTA) to no avail. When I run `|ota (sein:title our now our) %kids` from the child planet it just gives an instant success but the hash stays the same. When I run the same command from `~ripten` after a couple of minutes I get `ames: ~ten fragment crashed %exit`.

What is going on?

**Comment by philipcmonk** [comment]
Null base hash means you haven't been able to download any OTA, confirmed by your having a hash associated with a pill from March 9.  To solve this immediately (well, it'll take a minute to download), you can probably just switch your OTA source with `|ota ~bus %kids`.

If after this your base hash is correct but your home and kids hashes are not, run:

```
|merge %home ~bus %kids, =gem %only-that
|merge %kids ~bus %kids, =gem %only-that
```

Then you should stay in up-to-date going forward

The ames crashes are strange.  If they're still there after you're up-to-date, can you run `|ames-sift ~ten` and `|ames-verb %msg` and wait for the crash to happen again, that should give a stack trace.

**Comment by cxk280** [comment]
That did it! Thanks @philipcmonk . I did have to run the two extra commands to get `home` and `kids` hashes up to date.

Would the cause of this be that something is wrong with `~ten`? It always answers when I `|hi ~ten`, although not sure how much that necessarily signifies.

I am also still getting that ames error. When following your suggestion, I get the following stack trace: `ames: ~ten: plea [[~ripten 4] [~ten 4] bone=[4 %g /ge/ping]]`. What does that mean?

**Comment by philipcmonk** [comment]
That's a normal, expected message.  A stack trace would come after `ames: ~ten fragment crashed %exit`.  If it doesn't happen within a few minutes, you could try running `|merge %home ~ten %kids` to see if that triggers it.

~ten looks alright from my perspective, so I'm guessing there's something wrong specifically with the connection between ~ripten and ~ten.  We fixed a bug in that area about a month ago, but there may be another one.

**Comment by cxk280** [comment]
I think this is the stack trace we are looking for:

```
ames: ~ten fragment crashed %exit
/sys/vane/ames/hoon:<[2.114 7].[2.114 50]>
[%dangling-bone ~ten 416]
/sys/vane/ames/hoon:<[2.113 7].[2.114 50]>
/sys/vane/ames/hoon:<[2.112 7].[2.114 50]>
/sys/vane/ames/hoon:<[2.243 30].[2.243 45]>
/sys/vane/ames/hoon:<[2.243 24].[2.243 66]>
/sys/vane/ames/hoon:<[2.243 9].[2.258 21]>
/sys/vane/ames/hoon:<[2.240 9].[2.258 21]>
/sys/vane/ames/hoon:<[2.204 22].[2.204 63]>
/sys/vane/ames/hoon:<[2.203 13].[2.206 15]>
/sys/vane/ames/hoon:<[2.202 11].[2.207 37]>
/sys/vane/ames/hoon:<[2.201 11].[2.207 37]>
/sys/vane/ames/hoon:<[2.200 11].[2.207 37]>
/sys/vane/ames/hoon:<[2.199 11].[2.207 37]>
/sys/vane/ames/hoon:<[2.199 7].[2.322 9]>
/sys/vane/ames/hoon:<[2.196 7].[2.322 9]>
/sys/vane/ames/hoon:<[2.195 7].[2.322 9]>
/sys/vane/ames/hoon:<[2.194 7].[2.322 9]>
/sys/vane/ames/hoon:<[2.191 7].[2.322 9]>
/sys/vane/ames/hoon:<[2.188 7].[2.322 9]>
/sys/vane/ames/hoon:<[1.952 9].[1.952 65]>
/sys/vane/ames/hoon:<[1.947 9].[1.952 65]>
/sys/vane/ames/hoon:<[1.946 7].[1.964 69]>
/sys/vane/ames/hoon:<[1.944 7].[1.964 69]>
/sys/vane/ames/hoon:<[1.942 7].[1.964 69]>
/sys/vane/ames/hoon:<[1.939 7].[1.964 69]>
/sys/vane/ames/hoon:<[1.379 10].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.378 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.349 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
[%ames-crash-on-packet-from ~ten]
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[897 14].[897 53]>
/sys/vane/ames/hoon:<[895 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[880 3].[909 20]>
call: failed
bar-stack=~[~[//ames]]
[%poke %hear]
ames: ~ten: hear ~ten seq=1 1kb
```

**Comment by cxk280** [comment]
It looks like I can't get the OTA update to go to the planet correctly though. Tried running `|ota ~ripten %kids` on the planet, and it says it downloads the update, but the hash is still that weird hash that isn't a release.

**Comment by cxk280** [comment]
Also, how do I turn that automated stack trace off?

**Comment by philipcmonk** [comment]
`|ames-verb` with no arguments will turn that off.

So you're saying the child hash ends in `nlch2`?

**Comment by cxk280** [comment]
No, the child's hash is `0va.pul07.ph10n.dnbh7.78e73.hav2t.ae9ik.jegg5.dqm2t.5baqv.mnqtc`.

**Comment by philipcmonk** [comment]
That stack trace is unusual, it's saying that you're receiving a response on a channel (flow) you never opened.  The possible reasons that come to mind are:

1. you ran ~ripten in two places at some point (or copied it and ran both copies, even if not at the same time)
2. the last time you breached you only changed the keys and didn't breach
3. ~ten didn't hear about the last breach.
4. there's a bug in ames

I checked ~ten and it looks like (3) is not the case.  (4) is possible, though in my experience (1) and (2) are more common.

The next thing to check would be to see if both sides generally agree as to the number of flows between them.  The way to do this is run `|start %dbug`, then navigate to `/~debug`, go to the ames tab, search for ~ten, and see how many flows it lists.  From ~ten's perspective we show no forward bones and 209 backward bones (going up to bone number 417, which would show up as 416 on your side).

**Comment by philipcmonk** [comment]
Is that the child's base hash?  Or do they not have a base hash?

**Comment by cxk280** [comment]
> Is that the child's base hash? Or do they not have a base hash?

That's the planet's hash for base, sour, home, and kids.

When I follow your instructions for debug on `~ripten`, I see 6 forward bones and 0 backward bones. Which is...quite different than what is expected...

![Screen Shot 2021-03-29 at 4 33 46 PM](https://user-images.githubusercontent.com/19479857/112896602-98f68700-90ac-11eb-9611-616048a57233.png)

**Comment by philipcmonk** [comment]
There's definitely a significant disagreement!  A mishandled breach can cause this, but it looks like your last breach was in September, so that couldn't be it.  If this state is missing, it could explain why the planet is hasn't gotten the OTA upgrade either -- it could also have a dangling bone or something similar.

This means either there's a bug in ames that dropped a large portion of its state, or this pier hasn't had a linear history.  The original home hash you posted was from a pill from March 9, did you have ~ripten running before then (but after the network breach in December)?

It's a crude measurement, but your flow (bone) 4 is where "pings" are happening, and those happen roughly every 30 seconds as long as both ships are up.  Your dashboard shows 33,785 packet count, which would be about 12 days.  On ~ten it shows 206,682, which would be around 72 days.  Whatever caused the data loss probably happened about 2 weeks ago.

In any case, I think ~ripten will unfortunately need to breach.  If you're quite confident that ~ripten has only run in one place the whole time, you could send the pier to us and we could do partial replays of the event log, to check its debug state from eg a month ago and see if it ever had the right state.

**Comment by cxk280** [comment]
I can't remember exactly, but I almost certainly caused this by having the pier in multiple places at one time at some point while troubleshooting some unrelated SSL and load balancer stuff on AWS that was giving me DNS trouble. I'll breach it and see what happens. Is there anything I need to do on the children after doing the breach or should they be able to catch up automatically?

**Comment by philipcmonk** [comment]
They should catch up automatically, but do check.  The only issue I could imagine would be if some of them never got a "real" OTA since ~ripten stopped getting them.  I think it'll still handle that, but if not, they may get a "no merge base" error, which can be solved with these commands as before (run on any stuck planets this time):

```
|merge %home ~ripten %kids, =gem %only-that
|merge %kids ~ripten %kids, =gem %only-that
```

**Comment by jfranklin9000** [comment]
~ripten's life is 4 but its rift is 5.  That shouldn't be possible?

Anyway, I'm one of the child ships of ~ripten.  I did the `|merge` commands from ~marzod, and am OTAing from ~marzod too.  I'll switch back to ~ripten when it's up-to-date.

**Comment by philipcmonk** [comment]
> ~ripten's life is 4 but its rift is 5. That shouldn't be possible?

Something I noticed fairly recently is that if you run `configureKeys` with the same keys that you used before, it won't increment the life, but it will still breach if you set the `discontinuous` flag.  So, contrary to what I told some people (maybe including you?) it's possible for life or rift to advance independent of the other.

**Comment by jfranklin9000** [comment]
Yes, in https://groups.google.com/a/urbit.org/g/dev/c/4UIQxdURIO8/m/ghpSDaEoAgAJ
"There is currently no way to increment your rift without incrementing your life.[1]"

**Comment by cxk280** [comment]
Sorry for the delay here--day job got insane this week and I'm just catching up.

So after breaching and following @philipcmonk 's instructions, it looks like `~ripten` is all up to date. Thank you for your help! I'm to go ahead and close this out.
