### ISSUE TITLE
Can't reconnect to Hoon school

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#3]
sivtun-hannyr

**Comment by vvisigoth** [comment]
@rmariani looks like you moved this to "Seeking Fix" is it assigned to anyone?

**Comment by rmariani** [comment]
I move things to "seeking fix" if their fix may be forthcoming. Is this not
the idea?

—
~padmyn-pasnux
https://urbit.org

**Comment by rmariani** [comment]
Oh or that indicates the personal process of the fix being sought?

**Comment by vvisigoth** [comment]
yes it means "in progress"
—
~poldec-tonteg
http://urbit.org

**Comment by rmariani** [comment]
K will fix

—
~padmyn-pasnux
https://urbit.org

**Comment by baudtack** [comment]
This is a duplicate. This ship is a member of the group.
