### ISSUE TITLE
Can't reconnect to Hoon school

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#5]
~risnep-dirlux

**Comment by crrncllns** [comment]
error upon trying to re-join notebook:  %wire and non-uniqueness

**Comment by morelazers** [comment]
Not sure I'm too stoked with my email address being shared to the whole wide world, but I appreciate the intent 😅

**Comment by crrncllns** [comment]
Fixed!

**Comment by baudtack** [comment]
@morelazers I see you are part of the hoon school group. Are you still experiencing problems?

**Comment by morelazers** [comment]
Yep - I can see the chat but I can't see the notebook. This is the error I get when I try to join it manually from OS1.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/2966123/81029131-3827f400-8ec7-11ea-8f3b-190f49dfa496.png">

**Comment by baudtack** [comment]
Please provide the output of +trouble

**Comment by morelazers** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/2966123/81128021-5d7a3800-8f83-11ea-995e-7bf16c67b1cc.png">

**Comment by morelazers** [comment]
Had a couple of invites sitting in my OS1 - I'm back into Hoon School (two of them, in fact)! 

<img width="253" alt="image" src="https://user-images.githubusercontent.com/2966123/81815494-6368ae00-956d-11ea-8c5e-d3204f02bd65.png">

**Comment by morelazers** [comment]
Oh no I spoke too soon :(

I can get into the new chat room though!

<img width="413" alt="image" src="https://user-images.githubusercontent.com/2966123/81815856-df62f600-956d-11ea-9258-18f7deced952.png">


<img width="1046" alt="image" src="https://user-images.githubusercontent.com/2966123/81815884-ea1d8b00-956d-11ea-95bd-9c8443c3b283.png">

**Comment by baudtack** [comment]
Do you see the chat and notebook in groups when you click on hoon school 4?

**Comment by morelazers** [comment]
@baudtack I see the chat and notebook, but the notebook will not open (see screenshot). The chat works though.
